apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web-app
  namespace: python-web-app
  labels:
    app: python-web-app
  annotations:
    fluentbit.io/log-group-name: "/eks/python-web-app-logs"
    fluentbit.io/log-stream-prefix: "python-web-app"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-web-app
  template:
    metadata:
      labels:
        app: python-web-app
    spec:
      containers:
        - name: python-web-app  # ✅ Corrected container name
          image: <ECR_REPOSITORY_URL>:1.0.0
          ports:
            - containerPort: 8000
          resources:  # ✅ Added resource requests & limits
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ENVIRONMENT
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_KEY
            - name: AWS_LOG_GROUP
              value: "/eks/python-web-app-logs"
            - name: AWS_REGION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['topology.kubernetes.io/region']
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/app
      volumes:
        - name: log-volume
          emptyDir: {}
