apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web-app
  namespace: python-web-app
  labels:
    app: python-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-web-app
  template:
    metadata:
      labels:
        app: python-web-app
    spec:
      containers:
        - name: python-web-app
          image: <ECR_REPOSITORY_URL>:latest  # To be updated dynamically in GitHub Actions
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ENVIRONMENT
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_KEY
            - name: AWS_LOG_GROUP
              value: "/eks/python-web-app-logs"
            - name: AWS_REGION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['eks.amazonaws.com/region']
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/app
      volumes:
        - name: log-volume
          emptyDir: {}
      annotations:
        fluentbit.io/log-group-name: "/eks/python-web-app-logs"
        fluentbit.io/log-stream-prefix: "python-web-app"
